---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gofish/ioqueue
    docker:
      - image: circleci/golang:1.10
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: sudo apt-get install libaio-dev libgtest-dev cmake
      - run: (cd /usr/src/gtest/ && sudo cmake -DCMAKE_BUILD_TYPE=RELEASE . && sudo make)
      - run: sudo mv -nv /usr/src/gtest/libgtest* /usr/lib
      - run: make
      - run: make test
