---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make test
